### ISSUE TITLE
Colors break when convert GUI to xterm-256color

### ISSUE THREAD

**Issue by tuyenpm9** [KevinGoodsell/vim-csexact#13]
I try to convert a theme that support for GUI and also some fallback to terminal also it should work fairly with 256color. Unfortunately when I use this plugin and have this result:
![test](https://i.imgur.com/KQaP48h.png)

Can you see background color is totally broken. I tried to disable all other plugins and can confim this plugin caused the issue, work well with CSApprox.

**Comment by KevinGoodsell** [comment]
Not much I can do without the colorscheme file.

**Comment by tuyenpm9** [comment]
@KevinGoodsell : I use `vim-material-theme`.

I also changed the title, actually in terminal instead of console/tty - non-graphic environment.

In the end I realize I can't distinguish when have to many colors enabled, so I patched color theme different from gui version. So I'll close but you might want to have a look.

**Comment by KevinGoodsell** [comment]
I'm not sure I understand the previous comment about patching the theme. Was it a patched version that exhibited the problem? The theme appears to work fine when I try it. Or at least the first theme with that name I found in a google search appeared to work fine, no way of knowing if it was the same one.

**Comment by tuyenpm9** [comment]
Yes, that's theme from `jdkanani/vim-material-theme`, so probably I patched the theme so it broke somehow but the actual work behind patching is just use `highlight` command to get my own favor colors.
