### ISSUE TITLE
CSExact doesn't work with Solarized (or the default colorscheme, I think)

### ISSUE THREAD

**Issue by ahri** [KevinGoodsell/vim-csexact#9]
I get this error when doing `:colorscheme solarized`
```
Error from: function <SNR>23_CSExactCheck..<SNR>23_CSExactErrorWrapper..<SNR>23_CSExactRefresh..rethrow#Rethrow, line 11
Vim(echoerr):Vim(highlight):E420: BG color unknown
```

Sample .vimrc:
```
set nocompatible
filetype off

set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

" let Vundle manage Vundle
Plugin 'gmarik/Vundle.vim'

Plugin 'KevinGoodsell/vim-csexact'
Plugin 'altercation/vim-colors-solarized'

call vundle#end()
filetype plugin indent on " has to be after bundles

syntax on
```

I notice actually that if I start vim with `-u .vimrc-csexact-issue9` I don't even need to swap colorscheme to solarized; the above error happens for whatever the default colorscheme is.

I started Vim up with `-V10err.log` and took a look in there:
```
line 112: sourcing "/home/vagrant/.vim/bundle/vim-csexact/autoload/rethrow.vim"
finished sourcing /home/vagrant/.vim/bundle/vim-csexact/autoload/rethrow.vim
continuing in function <SNR>11_CSExactCheck..<SNR>11_CSExactErrorWrapper..<SNR>11_CSExactRefresh
Error from: function <SNR>11_CSExactCheck..<SNR>11_CSExactErrorWrapper..<SNR>11_CSExactRefresh..rethrow#Rethrow, line 11
Vim(echoerr):Vim(highlight):E420: BG color unknown
finished sourcing /home/vagrant/.vim/bundle/vim-csexact/plugin/CSExact.vim
```

I also noticed 35 lines of this in the log (previous to the above), which may be expected(?)
```
CSExact: Bad highlight line '^ILast set from /usr/share/vim/vim74/syntax/syncolor.vim'
```

**Comment by KevinGoodsell** [comment]
OK, I see the problem here. It was introduced with the regex change for the group name in the last commit. I'm surprised it only shows up on certain color schemes.

**Comment by ahri** [comment]
Man, that was quick!

I noticed that even when everything looks fine (with my default setup) I get those:
```
CSExact: Bad highlight line '^ILast set from ~/.vim/bundle/molokai/colors/molokai.vim
```
errors - so perhaps it's not an issue.

**Comment by KevinGoodsell** [comment]
ahri, that probably happens because verbose is set somehow. I think CSExact has probably done that all along, but it's probably worth addressing.

Another problem occurs when highlight groups are set with both specific attributes and a link to another group. I don't really recall how Vim interprets that, but I don't think it's actually useful.

    :highlight Boolean term=underline
    :highlight! link Boolean Constant
    :CSExactColors

    CSExact: Bad highlight line '                   links to Constant'

So we have three items, that I may split into different issues:

1. The new regex allows whitespace in group names, which causes the parsed names to be slightly wrong.
2. Verbose messages aren't parsed, and produce warnings.
3. Highlight groups with both specific attributes and a link to another group are not handled.

**Comment by KevinGoodsell** [comment]
I pushed fixes for 1 and 2. I need to look into 3 to figure out what the right behavior would be.

**Comment by KevinGoodsell** [comment]
Just pushed the fix for item 3. Tested with a bunch of colorschemes this time.

**Comment by ahri** [comment]
I just pulled your latest changes and everything looked fine, but I noticed a message coming up with changing colorscheme about bad highlights, so I switched verbose mode back on and saw this:

```
$ vim -V20foo.log
CSExact: Bad highlight line 'line 5:     " 0verbose turns off any verbose messages so we don't have to parse them.'
CSExact: Bad highlight line 'line 6:     0verbose silent highlight'
CSExact: Bad highlight line 'line 7:     redir END'

CSApprox: Exiting - high fg color found for Statement
Press ENTER or type command to continue
```

and then, upon changing colorscheme:
```
CSExact: Bad highlight line 'line 5:     " 0verbose turns off a
ny verbose messages so we don't have to parse them.'
CSExact: Bad highlight line 'line 6:     0verbose silent highlight'
CSExact: Bad highlight line '               xxx cleared'
CSExact: Bad highlight line 'line 7:     redir END'
```

I wasn't sure whether this was a problem, but I noticed that switching from my default, molokai, to molokai results in my airline colours being broken, so I think the bad highlight errors are halting processing. It seems to happen with the desert colorscheme too.

I can't really tell whether half of the problem is just in switching verbose mode on :(

**Comment by KevinGoodsell** [comment]
You're getting that because you have verbose logging turned on. It's sending verbose messages through the redirect, and I'm not sure why. Seems like bad behavior on Vim's part to me. I'm still looking at what controls this stuff, the help isn't very clear.

**Comment by KevinGoodsell** [comment]
Just pushed 8632827 to eliminate the warnings.

**Comment by ahri** [comment]
Sorry I took a while coming back. It all looks fixed now!
